

const About = () => {
    return ( 
        <div className="Abouttext">
            <h2><u>About us</u></h2>
            <p className="Abouttextp">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec nec venenatis nibh. Aliquam sed felis et lectus viverra dignissim. Integer non vehicula metus. Proin luctus blandit nibh. Suspendisse ac purus eget felis molestie porta vel at lacus. Sed et lobortis sem. Suspendisse eget tincidunt elit. Pellentesque posuere velit quis odio commodo, eget dapibus sem convallis. Etiam faucibus rutrum ipsum, quis viverra sapien aliquam vel. Morbi tincidunt, purus eget consequat commodo, elit urna interdum mi, in ornare sem est sit amet felis. Sed vel vulputate odio. Phasellus maximus ligula felis, sed ultricies quam elementum vel. Etiam nec hendrerit erat. Aliquam eget lectus a dui dictum congue eu non metus. Sed ut nunc neque. Aenean ut est scelerisque libero molestie accumsan sed non elit.
                Phasellus laoreet in mi in pellentesque. Aliquam vitae sapien magna. Maecenas ultrices, elit sed porttitor fermentum, nunc lacus aliquam est, eget commodo orci lacus vel metus. Fusce pretium efficitur libero, in imperdiet quam. Integer malesuada vestibulum libero quis porta. Quisque posuere convallis urna, eget blandit arcu accumsan ullamcorper. Praesent ipsum sapien, iaculis mollis iaculis ut, eleifend ac urna. Vivamus vestibulum dignissim odio quis porttitor. Praesent finibus leo ut pulvinar tincidunt. Duis commodo semper purus ut iaculis. Vestibulum finibus aliquet luctus. Praesent imperdiet lacus eget iaculis tempus. Nullam eu convallis leo, ut ultricies massa.
                In sit amet molestie augue. Nunc elit justo, scelerisque et gravida eu, bibendum a odio. Cras aliquet, neque ut interdum gravida, odio elit molestie nisi, non ultricies quam est sed diam. Fusce auctor sit amet mi non euismod. Nullam ipsum massa, consectetur quis metus ut, feugiat pharetra tellus. Suspendisse nulla orci, laoreet in purus sed, feugiat commodo metus. Vestibulum eu condimentum felis, in fringilla urna. Praesent at cursus dolor. Nam placerat lobortis nunc eget sodales. Sed convallis, lacus sit amet maximus sollicitudin, odio leo auctor.Donec in lorem mollis, laoreet nunc non, convallis odio. Nam luctus felis quis porttitor semper. Nullam consectetur nisi id aliquam congue. Pellentesque imperdiet eros nisl, vehicula fringilla urna bibendum ac. Ut sit amet dolor quis ipsum lobortis tincidunt. Maecenas dolor risus, varius eget tellus et, tristique ultrices eros. Nulla facilisi. Nam aliquet orci in neque ornare, quis lobortis tellus laoreet. Etiam finibus tortor aliquet metus suscipit, eget vulputate nisl eleifend. Donec non porta elit. Aliquam erat volutpat. Quisque nec pellentesque elit. Praesent tincidunt nibh eu volutpat eleifend. Mauris congue gravida ante, faucibus mollis tellus auctor eget. Curabitur egestas, tortor sed egestas.</p>
        </div>
     );
}
 
export default About;